services:
  backend:
    build: ./backend
    container_name: profile-backend
    environment:
      MONGO_URL: mongodb://mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: profile-mongo
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
